[package]
name = "numng"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.22"
nuon = {version = "0.101.0", optional = true}
serde = {version = "1.0.217", features = ["derive"]}
serde_json = "1.0.134"
